import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F6F8",
    padding: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#004272",
    textAlign: "center",
    marginBottom: 8,
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    marginVertical: 8,
    padding: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.09,
    shadowRadius: 4,
  },
  apartmentLabel: {
    fontSize: 18,
    fontWeight: "600",
    color: "#004272",
  },
  apartmentSubLabel: {
    fontSize: 14,
    color: "#6c889c",
    marginTop: 2,
  },
  createButton: {
    backgroundColor: "#004272",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    paddingVertical: 13,
    marginTop: 10,
    marginBottom: 15,
  },
  createButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 8,
    letterSpacing: 0.5,
  },
  // Formulario
  formContainer: {
    backgroundColor: "#F4F6F8",
    flex: 1,
    padding: 28,
    justifyContent: "center",
  },
  formTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#004272",
    marginBottom: 22,
    textAlign: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: "#BBC7D0",
    backgroundColor: "#fff",
    padding: 12,
    marginBottom: 15,
    borderRadius: 8,
    fontSize: 16,
    color: "#1a1a1a",
  },
  statusSelector: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 22,
    marginTop: 5,
  },
  statusOption: {
    backgroundColor: "#e4ebf7",
    color: "#004272",
    fontWeight: "500",
    borderRadius: 6,
    paddingHorizontal: 16,
    paddingVertical: 8,
    textAlign: "center",
    fontSize: 15,
  },
  selectedStatus: {
    backgroundColor: "#004272",
    color: "#fff",
    fontWeight: "700",
    borderRadius: 6,
    paddingHorizontal: 16,
    paddingVertical: 8,
    textAlign: "center",
    fontSize: 16,
  },
  formButton: {
    backgroundColor: "#004272",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 8,
    marginBottom: 6,
  },
  formButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 7,
  },
  cancelButton: {
    backgroundColor: "#e4ebf7",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
  },
  cancelButtonText: {
    color: "#004272",
    fontWeight: "600",
    fontSize: 15,
  },
  modalOverlay: {
  flex: 1,
  backgroundColor: "rgba(0,0,0,0.32)",
  justifyContent: "center",
  alignItems: "center",
  },
  modalCard: {
    width: 280,
    backgroundColor: "#fff",
    borderRadius: 15,
    paddingVertical: 22,
    paddingHorizontal: 18,
    alignItems: "center",
    elevation: 8,
  },
  modalOptionBtn: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 8,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#e4ebf7",
    width: "100%",
    justifyContent: "center",
  },
  modalOptionText: {
    color: "#004272",
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 7,
    letterSpacing: 0.4,
  },
  modalOptionDanger: {
    backgroundColor: "#fde6e6",
  },
  modalCloseBtn: {
    marginTop: 15,
    color: "#999",
    fontWeight: "bold",
    fontSize: 15,
  },
});
