import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f4f6f8", padding: 20 },
  title: { fontSize: 22, fontWeight: "bold", marginBottom: 16, color: "#004272" },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 3,
    elevation: 1,
  },
  cardIcon: { marginRight: 14 },
  cardTitle: { fontWeight: "bold", color: "#004272", fontSize: 15 },
  cardDesc: { color: "#4a6373", fontSize: 13 },
  cardStatus: { color: "#5f7796", fontSize: 13, marginVertical: 1 },
  cardAmount: { fontWeight: "bold", fontSize: 15, marginHorizontal: 6 },
  payBtn: {
    backgroundColor: "#39c079",
    marginLeft: 8,
    borderRadius: 7,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  emptyText: { textAlign: "center", marginTop: 40, color: "#5f7796" },

  overlay: {
  flex: 1,
  backgroundColor: "rgba(0,0,0,0.29)",
  justifyContent: "center",
  alignItems: "center",
},
formCard: {
  backgroundColor: "#fff",
  borderRadius: 16,
  width: "90%",
  maxWidth: 400,
  padding: 25,
  elevation: 10,
  alignItems: "center",
  shadowColor: "#000",
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.15,
  shadowRadius: 12,
},
formTitle: {
  fontSize: 18,
  fontWeight: "bold",
  color: "#00746a",
  marginBottom: 16,
  textAlign: "center",
},
inputLabel: {
  color: "#004272",
  fontWeight: "600",
  marginBottom: 4,
  marginTop: 14,
  marginLeft: 2,
},
input: {
  borderWidth: 1,
  borderColor: "#d5e0ec",
  borderRadius: 8,
  backgroundColor: "#f7fafd",
  padding: 10,
  width: "100%",
  fontSize: 15,
  marginBottom: 3,
},
formButton: {
  backgroundColor: "#25b884",
  borderRadius: 10,
  paddingVertical: 10,
  paddingHorizontal: 15,
  alignItems: "center",
  flexDirection: "row",
  justifyContent: "center",
  marginTop: 20,
  width: "100%",
},
formButtonText: {
  color: "#fff",
  fontWeight: "bold",
  fontSize: 16,
  marginLeft: 6,
},
cancelButton: {
  marginTop: 13,
  alignItems: "center",
},
cancelButtonText: {
  color: "#999",
  fontWeight: "600",
},

});
